dataset:
  root_dir: benchmark/NeRF_example/nerf_llff_data/fern
  dataset_name: llff
  img_wh: [504, 378]
render:
  N_samples: 64
  N_importance: 64
  perturb: 1.0
  noise_std: 1.0
  batch_size: 1024
  white_back: False
train:
  num_epochs: 50
  loss_type: 'mse'
  # loss_type: 'robust_loss'
  model: 'nerf'
  # model: 'siren'
  # model: 'gaussian_nerf'
exp:
  exp_name: fern_
